org: ${env:SLS_ORG}
app: codecov-examples
service: impact-python-example

frameworkVersion: '3'

custom:
  wsgi:
    app: example-app.app.app

provider:
  name: aws
  runtime: python3.9

functions:
  api:
    handler: wsgi_handler.handler
    environment:
      CODECOV_OPENTELEMETRY_TOKEN: ${env:CODECOV_OPENTELEMETRY_TOKEN}
      SERVERLESS: true
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-wsgi
  - serverless-python-requirements